apiVersion: v1
kind: Namespace
metadata: 
  name: lab-pcc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nest-test-pcc
  namespace: lab-pcc
  labels:
    app: backend-nest-test-pcc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-nest-test-pcc
  template:
    metadata:
      labels:
        app: backend-nest-test-pcc
    spec:
      containers: 
      - name: backend-nest-test-pcc
        image: us-west1-docker.pkg.dev/lab-agibiz/docker-repository/backend-nest-test-pcc
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-nest-svc
  namespace: lab-pcc
  labels:
    app: backend-nest-svc
spec:
  selector:
     app: backend-nest-test-pcc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-nest-test-pcc
  namespace: lab-pcc
spec:
  ingressClassName: nginx
  rules:
  - host: pcc.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-nest-svc
            port:
              number: 80